### ISSUE TITLE
No easy way to write unit tests for code using sms package

### ISSUE THREAD

**Issue by i512** [messagebird/go-rest-api#110]
Currently `sms` provides package-level methods for managing messages. Client needs to be provided with every request.
This does not allow users to mock the client because there is **no interface**. 

The only way to test this package is to either wrap it in a sane client that can be provided as an interface or to provide a test http client to the `sms` package itself. The former doesn't really test actual calls and the latter requires you to parse and write json responses which sucks big time.

**Comment by vallerion** [comment]
Since version 9 all functions expect `messagebird.Client` interface.
