### ISSUE TITLE
Not setting ScheduledDatetime on voicemessage causes delayed sending

### ISSUE THREAD

**Issue by iivvoo** [messagebird/go-rest-api#112]
If, when sending a VoiceMessage, no ScheduledDatetime is set (or if one is set into the very near future or past), the voicemessage is delayed by up to a minute - it is not sent immediately/as soon as possible as would be logical.

This is most likely because the backend will schedule a task to send the message in stead of sending it immediately, even if the ScheduledDatetime is already in the past. And since the zero ScheduledDatetime is not checked with `IsZero()`, as is done when sending SMS messages, it will default  to `0001-01-01T00:00:00Z` which, as suggested above, will probably be scheduled and picked up later in stead of sent immediately.

I've provided a fix + test in #108. Since this PR seems to be mostly ignored, I've created this issue to clarify the bug. It would be nice if this could be merged so I don't have to depend on my fork any further.

Additionally, the backend team might want to look into how to deal with handling messages that are Scheduled in the past, but that's beyond the scope of the Go REST API.

**Comment by rfeiner** [comment]
Thanks for the PR. Merged today. Apologies again for the delay.
