### ISSUE TITLE
Advanced error handling, documentation invalid ?

### ISSUE THREAD

**Issue by StratoNET** [messagebird/go-rest-api#118]
Advanced error handling documentation (example as given in ReadMe.md)... sms does not have a Read method, so cannot be followed as per example. Is documentation out of date ? Does v7 have alternate error handling method ? regards

**Comment by vallerion** [comment]
Hi @StratoNET, is it still relevant to you? Actually sms have a Read method and you can do it like this:
```go
...
message, err := sms.Read(client, "messageId")
if err != nil {
	// Handle error.
	return
}

fmt.Println(message.ID)
```
