### ISSUE TITLE
Recipients Price type is INT but in sms returned the value is double

### ISSUE THREAD

**Issue by chuckwhisler** [messagebird/go-rest-api#125]
Recipients Price type is INT but in sms returned the value is double cannot decode due to this issue getting json unmarshal error

**Comment by chuckwhisler** [comment]
Value returned from sms.Read() function in which Recipients have price of message it's in double but struct of Price is in int

**Comment by vallerion** [comment]
Hi @chuckwhisler! I prepared MR and going to merge it in nearest time
https://github.com/messagebird/go-rest-api/pull/126

**Comment by chuckwhisler** [comment]
Thank you very much :+1:

**Comment by vallerion** [comment]
Published release for the update: https://github.com/messagebird/go-rest-api/releases/tag/v9.1.1
