### ISSUE TITLE
Status of add-voice-api-functions branch

### ISSUE THREAD

**Issue by raja** [messagebird/go-rest-api#21]
Our team is curious about the status of the [voice-api branch](https://github.com/messagebird/go-rest-api/tree/add-voice-api-functions). 

Is this being actively worked on? What is the current status? We are happy to contribute towards feature completeness. Can this branch be updated with merges back from master?

**Comment by polyfloyd** [comment]
Hello!

Work on the `add-voice-api-functions` has stagnated for a while and as a result, making it difficult to merge with the current master.

I'm going to start working on this. Will update this issue when I have new information.

**Comment by polyfloyd** [comment]
The Voice API has been added in #27.
