### ISSUE TITLE
Full call recording

### ISSUE THREAD

**Issue by raja** [messagebird/go-rest-api#30]
I was told by Sam @ MessageBird that full call recording is now supported but unsure how to implement with the go-rest-api. Perhaps something needs to be added to the package?

> Yes, I'm glad to report that full call recording has been added. To enable full call recording, just set `record: true` as a property in your call flow, and you should be good to go. 

I tried adding an empty CallFlowRecordStep{} to no avail.

**Comment by polyfloyd** [comment]
Hey,

Full call recording has been a fairly recent addition to the Voice API. Therefore, it seems to not be incorporated in the Go client yet.

**Comment by raja** [comment]
i'm happy to fork and and send a PR. Does the record: true property go into the parent call flow (not call flow steps)? I couldn't find this in the documentation outside the email from @samwierema

**Comment by polyfloyd** [comment]
Hey @raja,

Yes, the `record` property of a `CallFlow` toggles whether the full call is recorded. We just merged PR #31 to implement support for this property.
