### ISSUE TITLE
Proposal: replace ErrResponse in client with instance of ErrorResponse struct

### ISSUE THREAD

**Issue by romanyx** [messagebird/go-rest-api#34]
Hey! What do you think about replacing [`ErrResponse`](https://github.com/messagebird/go-rest-api/blob/master/client.go#L54) error variable in [`Client.Request`](https://github.com/messagebird/go-rest-api/blob/master/client.go#L150) method with instance of `ErrorResponse` structure which will contain `Errors []Error` property and will implement error interface.

```go
// ErrorResponse represents errored API response.
type ErrorResponse struct {
	Errors []Error `json:"errors"`
 }
 
 // Error implements error interface.
 func (r ErrorResponse) Error() string {
	return errorMessage
 }
```

So [error case](https://github.com/messagebird/go-rest-api/blob/master/client.go#L147) in the `Client.Request` method will be handled as 

``` go
var errorResponse ErrorResponse
if err := json.Unmarshal(responseBody, &errorResponse); err != nil {
	return err
}
 
return errorResponse
```

There will be ability to get rid of [checks](https://github.com/messagebird/go-rest-api/blob/master/client.go#L274) in the other methods and `Errors` property from models will be removed. But this change should be tagged as next version because this will make package incompatible.

**Comment by polyfloyd** [comment]
Hey @romanyx,

I am very much in favor. This is indeed a breaking change which requires a version bump.

If we deprecate `ErrResponse` and all associated struct fields and leave them in, we can reduce breakage if we assert that code that uses this library checks both returned the error by comparing it to `nil` in addition of `ErrResponse`.

**Comment by romanyx** [comment]
I think we can add new factory method like ‘NewV2’ for now which will return pointer to ‘Client’ instance with redefined ‘Request’ method which will return ‘ErrorResponse’ instance as the error at last return. Other methods will handle this properly as I can see. And ‘NewV2’ could be deprecated after version 2 release.
