### ISSUE TITLE
`Error` struct difference with server response

### ISSUE THREAD

**Issue by xlebenny** [messagebird/go-rest-api#62]
Sorry of my English,

I using the code like below to show the error message:
````golang
if err != nil {
	switch errResp := err.(type) {
	case messagebird.ErrorResponse:
		for _, mbError := range errResp.Errors {
			fmt.Printf("Error: %#v\n", mbError)
		}
	}

	return
}
````

I got this without **Error Message**
`Error: messagebird.Error{Code:18, Description:"", Parameter:""}`

But actually, your server has response the **Error Message**
So `Error` struct should be
````
type Error struct {
	Code        int
	Description string
	Parameter   string
	Message     string //<-- add this
}
````

Then will better 
`Error: messagebird.Error{Code:18, Description:"", Parameter:"", Message:"Parameter `source` has invalid number."}`

Happy coding

**Comment by epels** [comment]
HI @xlebenny, the way this SDK handles error responses seems to be consistent with what should be returned according to the API [docs](https://developers.messagebird.com/docs/errors).

If I understand your issue correctly, you're getting a response from our API that contains a `message` field describing the error, which is not properly unmarshaled by this SDK.
On what endpoint are you observing this behaviour? Can you help us reproduce the issue?

Thanks!

**Comment by xlebenny** [comment]
Hi @epels,

> If I understand your issue correctly, you're getting a response from our API that contains a `message` field describing the error, which is not properly unmarshaled by this SDK.
Yes

> On what endpoint are you observing this behaviour? Can you help us reproduce the issue?
[Here](https://github.com/xlebenny/messagebird-go-rest-api-62), only copy from [tutorial](https://github.com/messagebirdguides/voice-call-guide-go/blob/master/main.go) with `go mod init`
The balance API in your [README.md](https://github.com/messagebird/go-rest-api/blame/master/README.md#L42) is follow properly in your doc, but voice it look like not

Thanks for support.

**Comment by epels** [comment]
Thanks @xlebenny, you're absolutely right: the voice API uses `message` in error payloads rather than `description`, as this SDK assumes. This is an oversight on our part. We will pick this up and notify you here when it is fixed.
