### ISSUE TITLE
prop:question Release 5.3.0 vs Release 5.5.0

### ISSUE THREAD

**Issue by remotejob** [messagebird/go-rest-api#86]
I install API by command:
`go get github.com/messagebird/go-rest-api  ---> Release 5.3.0 ` 

But it looks like not support WhatsApp Sandbox ?

`client.EnableFeatures(messagebird.FeatureConversationsAPIWhatsAppSandbox)`

give me
`client.EnableFeatures undefined (type *messagebird.Client has no field or method EnableFeatures)` 

Questions: I must install Release 5.5.0 ? Best way to do it ?

I use go 1.14

**Comment by adis-me** [comment]
I had the same issue, but my go project was complaining about `voice.ErrorResponse`. It kept downloading v.5.3.0, so I forced to `go get` newest release:

```bash
go get github.com/messagebird/go-rest-api@7680f5abd53d0a086198d9baf42d848ca5160f1c
```

**Comment by remotejob** [comment]
I resolve it by installing locally  go-rest-api
and 
in go.mod:
-------------------------------------------------------
go 1.14

require "github.com/messagebird/go-rest-api" v5.3.0+incompatible
replace "github.com/messagebird/go-rest-api" v5.3.0+incompatible => "/home/juno/gowork/src/github.com/go-rest-api"
---------------------------------------------------------

But yours solution better.

**Comment by vallerion** [comment]
seems to be solved in https://github.com/messagebird/go-rest-api/pull/91
