### ISSUE TITLE
prop:Help can't make call and play wav file

### ISSUE THREAD

**Issue by remotejob** [messagebird/go-rest-api#89]
I try make call using .wav file but call hangup without playing file
`	source, destination := "3586004142", "358451202801"

	callflow := voice.CallFlow{
		Title: "Test flow",

		Steps: []voice.CallFlowStep{
			&voice.CallFlowPlayStep{
				// Media: "file_example_WAV_1MG.wav",
				Media: "https://file-examples.com/wp-content/uploads/2017/11/file_example_WAV_1MG.wav",

			},
		},
	}

	webhook := &voice.Webhook{
		URL: "http://97698bd2db6f.ngrok.io/smsstat",
		Token: "token",
	}

	call, err := voice.InitiateCall(
	    client,
	    source,
	    destination,
		callflow,
		webhook,
			
	)`

file: file_example_WAV_1MG.wav
RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 8000 Hz

**Comment by sarathsp06** [comment]
Is it still a concern?   what is the response from API?

**Comment by vallerion** [comment]
no answers and out of date, so closed
