### ISSUE TITLE
Package description is missing

### ISSUE THREAD

**Issue by cooldarkdryplace** [messagebird/go-rest-api#9]
Standard place for packages documentation _de facto_ is godoc.org. [API description](https://godoc.org/github.com/messagebird/go-rest-api) is not sufficient there, so I propose to add separate `doc.go` file with general description and link to [documentation](https://developers.messagebird.com/docs/introduction).

**Comment by samwierema** [comment]
I think that would be a bit of overkill? We could add the necessary documentation to the library (like you've done) and point users to the MessageBird developers portal there.

Besides, the `README.md` also includes the relevant links to the documentation.

**Comment by bilinguliar** [comment]
Yes I am talking about adding package description to the library. It will be parsed by godoc.org automatically. And if package description is not to big there is no real need in separate doc.go file of course.

> GoDoc generates documentation from Go source code.
> GoDoc checks for package updates once per day.

**Comment by bilinguliar** [comment]
I have added really basic package description in PR https://github.com/messagebird/go-rest-api/pull/8
If there are no plans to generate full documentation as godoc then I assume issue should be closed.

**Comment by cooldarkdryplace** [comment]
Resolved in https://github.com/messagebird/go-rest-api/pull/8
